### ISSUE TITLE
Branches/Forks

### ISSUE THREAD

**Issue by IzzySoft** [SebKuzminsky/rsync-push-backup#7]
Looks like we didn't see each other, and thus duplicated efforts (see [this timeline](https://github.com/SebKuzminsky/rsync-push-backup/network)). Just that you went ahead and already implemented what I had planned next (modules). Do you think we can reunite the branches (or rather forks) – or should I rather abandon mine? Yours basically includes all the "feature enhancements" I did, and more. But mine adds a little more documentation. So maybe there are things you want to cherry-pick. According to the timeline, you're the "uplink of my uplink", the latter just merged my PR, so it should be "right at your fingertips".

**Comment by IzzySoft** [comment]
PS: I've already referenced this issue from the other end (see above), but you might wish to [chime in here](https://github.com/tpapp/rsync-push-backup/pull/1) for additional details. Thanks in advance!

**Comment by SebKuzminsky** [comment]
Hi Izzy, i'd love to combine efforts and get all improvements into one consolidated repo, and to continue to collaborate in the future.

I'd like to also pull @bragr and @mikaellanger (the owners of the other to related repos) into this conversation and see if they're interested in merging & collaborating.

Let's continue this conversation in tpapp/rsync-push-backup#1 just to keep it all in one place.

**Comment by IzzySoft** [comment]
Good point – so we shall do! Thanks!
